FROM python:3

WORKDIR /usr/src/app

RUN git clone "https://github.com/WormStan/flask-utilities.git" "flask-utilities"

RUN pip install --no-cache-dir -r "./flask-utilities/webservice/requirements.txt"

WORKDIR /usr/src/app/flask-utilities/webservice

CMD git pull && gunicorn service:app -c gunicorn.conf.py

